name: parlour Scheduled Run
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
    reporter:
        runs-on: ubuntu-latest
        name: Scraping The Parlour's menu
        steps:
          - uses: actions/checkout@v3
          - name: Set up R ${{ matrix.r-version }}
            uses: r-lib/actions/setup-r@v4.2.3
            with:
              r-version: ${{ matrix.r-version }}
              http-user-agent: ${{ matrix.config.http-user-agent }}
              use-public-rspm: true
          - name: Install libcurl
            run: sudo apt-get install libcurl4-openssl-dev libssl-dev libicu-dev libxml2-dev
          - uses: r-lib/actions/setup-pandoc@v2
          - name: Install base dependencies
            run: |
              Rscript -e 'install.packages(c("dplyr","lubridate","remotes","twilio","readr","rvest","usethis","stringr"))'
            env:
              GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          - name: Pull data and update files
            run: Rscript ./R/todays_menu.R
            env:
              TWILIO_SID: ${{ secrets.TWILIO_SID }}
              TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
              from_number: ${{ secrets.from_number }}
              my_number: ${{ secrets.my_number }}
              friend_number: ${{ secrets.friend_number }}
          - name: Commit files
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "Github Action"
              git pull
              git add ./data/.
              git commit -m "Updated The Parlour's daily menu after latest bot run." || echo "No changes to commit"
          - name: Push updated files
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
